describe("AutoSuspend widget tests", function()
    setup(function()
        require("commonrequire")
        package.unloadAll()
        require("dbg"):turnOn()
    end)

    teardown(function()
        require("mock_time"):uninstall()
    end)

    it("should be able to execute suspend when timing out", function()
        local Device = require("device")
        stub(Device, "isKobo")
        Device.isKobo.returns(true)
        G_reader_settings:saveSetting("auto_suspeend_timeout_seconds", 10)
        local mock_time = require("mock_time")
        mock_time:install()
        local widget_class = dofile("plugins/autosuspend.koplugin/main.lua")
        local widget = widget_class:new()
        local UIManager = require("ui/uimanager")
        stub(UIManager, "suspend")
        mock_time:increase(11)
        UIManager:handleInput()
        assert.stub(UIManager.suspend).was.called(1)
        mock_time:uninstall()
        UIManager.suspend:revert()
        Device.isKobo:revert()
        G_reader_settings:delSetting("auto_suspend_timeout_seconds")
    end)

    it("should be able to initialize several times", function()
        local Device = require("device")
        stub(Device, "isKobo")
        Device.isKobo.returns(true)
        G_reader_settings:saveSetting("auto_suspeend_timeout_seconds", 10)
        local mock_time = require("mock_time")
        mock_time:install()
        -- AutoSuspend plugin set the last_action_sec each time it is initialized.
        local widget_class = dofile("plugins/autosuspend.koplugin/main.lua")
        local widget1 = widget_class:new()
        -- So if one more initialization happens, it won't sleep after another 5 seconds.
        mock_time:increase(5)
        local widget2 = widget_class:new()
        local UIManager = require("ui/uimanager")
        stub(UIManager, "suspend")
        mock_time:increase(6)
        UIManager:handleInput()
        assert.stub(UIManager.suspend).was.called(1)
        mock_time:uninstall()
        UIManager.suspend:revert()
        Device.isKobo:revert()
        G_reader_settings:delSetting("auto_suspend_timeout_seconds")
    end)
end)
