describe("BackgroundRunner widget tests", function()
    setup(function()
        require("commonrequire")
        package.unloadAll()
    end)

    teardown(function()
        package.unloadAll()
    end)
end)
