describe("docsettings module", function()
    local docsettings
    setup(function()
        require("commonrequire")
        docsettings = require("docsettings")
    end)
    it("should generate sidecar directory path", function()
        assert.Equals("../../foo.sdr", docsettings:getSidecarDir("../../foo.pdf"))
        assert.Equals("/foo/bar.sdr", docsettings:getSidecarDir("/foo/bar.pdf"))
        assert.Equals("baz.sdr", docsettings:getSidecarDir("baz.pdf"))
    end)
end)
