require("commonrequire")
local DEBUG = require("dbg")
local Font = require("ui/font")

describe("Font module", function()
    local f = nil
    it("should get face", function()
        f = Font:getFace('cfont', 18)
        assert.are_not.equals(f.ftface, nil)
        f = Font:getFace('tfont', 16)
        assert.are_not.equals(f.ftface, nil)
        f = Font:getFace('hfont', 12)
        assert.are_not.equals(f.ftface, nil)
    end)
end)
