describe("Japanese deinflector", function()
    local Deinflector

    setup(function()
        require("commonrequire")
        package.path = "plugins/japanese.koplugin/?.lua;" .. package.path
        Deinflector = require("deinflector"):new()
    end)

    -- Check that deinflecting `source` produces `term` somewhere in the results.
    -- Uses deinflectVerbatim (no kana conversion) for precise rule testing.
    local function deinflectsTo(source, term)
        local results = Deinflector:deinflectVerbatim(source)
        for _, r in ipairs(results) do
            if r.term == term then
                return true
            end
        end
        return false
    end

    -- Check that deinflecting `source` with full text conversions produces `term`.
    local function deinflectsFull(source, term)
        local results = Deinflector:deinflect(source)
        for _, r in ipairs(results) do
            if r.term == term then
                return true
            end
        end
        return false
    end

    -- ================================================================
    -- i-adjectives (adj-i)
    -- ================================================================
    describe("i-adjectives", function()
        -- 高い (takai, expensive/tall)
        it("should handle identity", function()
            assert.is_true(deinflectsTo("高い", "高い"))
        end)
        it("should deinflect negative: 高くない → 高い", function()
            assert.is_true(deinflectsTo("高くない", "高い"))
        end)
        it("should deinflect past: 高かった → 高い", function()
            assert.is_true(deinflectsTo("高かった", "高い"))
        end)
        it("should deinflect te-form: 高くて → 高い", function()
            assert.is_true(deinflectsTo("高くて", "高い"))
        end)
        it("should deinflect adverbial: 高く → 高い", function()
            assert.is_true(deinflectsTo("高く", "高い"))
        end)
        it("should deinflect conditional: 高ければ → 高い", function()
            assert.is_true(deinflectsTo("高ければ", "高い"))
        end)
        it("should deinflect noun form: 高さ → 高い", function()
            assert.is_true(deinflectsTo("高さ", "高い"))
        end)
        it("should deinflect -sou: 高そう → 高い", function()
            assert.is_true(deinflectsTo("高そう", "高い"))
        end)
        it("should deinflect -sugiru: 高すぎる → 高い", function()
            assert.is_true(deinflectsTo("高すぎる", "高い"))
        end)
        it("should deinflect -tara: 高かったら → 高い", function()
            assert.is_true(deinflectsTo("高かったら", "高い"))
        end)
        it("should deinflect -tari: 高かったり → 高い", function()
            assert.is_true(deinflectsTo("高かったり", "高い"))
        end)
        it("should deinflect polite negative: 高くありません → 高い", function()
            assert.is_true(deinflectsTo("高くありません", "高い"))
        end)
        it("should deinflect -ki (archaic): 高き → 高い", function()
            assert.is_true(deinflectsTo("高き", "高い"))
        end)

        -- 美しい (utsukushii, beautiful) - tests multi-kana stems
        it("should deinflect negative: 美しくない → 美しい", function()
            assert.is_true(deinflectsTo("美しくない", "美しい"))
        end)
        it("should deinflect past: 美しかった → 美しい", function()
            assert.is_true(deinflectsTo("美しかった", "美しい"))
        end)
        it("should deinflect -ge: 美しげ → 美しい", function()
            assert.is_true(deinflectsTo("美しげ", "美しい"))
        end)
    end)

    -- ================================================================
    -- Ichidan verbs (v1) — "ru-verbs"
    -- ================================================================
    describe("ichidan verbs", function()
        -- 食べる (taberu, eat)
        it("should handle identity", function()
            assert.is_true(deinflectsTo("食べる", "食べる"))
        end)
        it("should deinflect negative: 食べない → 食べる", function()
            assert.is_true(deinflectsTo("食べない", "食べる"))
        end)
        it("should deinflect past: 食べた → 食べる", function()
            assert.is_true(deinflectsTo("食べた", "食べる"))
        end)
        it("should deinflect te-form: 食べて → 食べる", function()
            assert.is_true(deinflectsTo("食べて", "食べる"))
        end)
        it("should deinflect polite: 食べます → 食べる", function()
            assert.is_true(deinflectsTo("食べます", "食べる"))
        end)
        it("should deinflect polite negative: 食べません → 食べる", function()
            assert.is_true(deinflectsTo("食べません", "食べる"))
        end)
        it("should deinflect polite past: 食べました → 食べる", function()
            assert.is_true(deinflectsTo("食べました", "食べる"))
        end)
        it("should deinflect polite past negative: 食べませんでした → 食べる", function()
            assert.is_true(deinflectsTo("食べませんでした", "食べる"))
        end)
        it("should deinflect polite volitional: 食べましょう → 食べる", function()
            assert.is_true(deinflectsTo("食べましょう", "食べる"))
        end)
        it("should deinflect conditional: 食べれば → 食べる", function()
            assert.is_true(deinflectsTo("食べれば", "食べる"))
        end)
        it("should deinflect volitional: 食べよう → 食べる", function()
            assert.is_true(deinflectsTo("食べよう", "食べる"))
        end)
        it("should deinflect imperative: 食べろ → 食べる", function()
            assert.is_true(deinflectsTo("食べろ", "食べる"))
        end)
        it("should deinflect imperative (yo): 食べよ → 食べる", function()
            assert.is_true(deinflectsTo("食べよ", "食べる"))
        end)
        it("should deinflect causative: 食べさせる → 食べる", function()
            assert.is_true(deinflectsTo("食べさせる", "食べる"))
        end)
        it("should deinflect passive/potential: 食べられる → 食べる", function()
            assert.is_true(deinflectsTo("食べられる", "食べる"))
        end)
        it("should deinflect -tai: 食べたい → 食べる", function()
            assert.is_true(deinflectsTo("食べたい", "食べる"))
        end)
        it("should deinflect -nasai: 食べなさい → 食べる", function()
            assert.is_true(deinflectsTo("食べなさい", "食べる"))
        end)
        it("should deinflect -sou: 食べそう → 食べる", function()
            assert.is_true(deinflectsTo("食べそう", "食べる"))
        end)
        it("should deinflect -sugiru: 食べすぎる → 食べる", function()
            assert.is_true(deinflectsTo("食べすぎる", "食べる"))
        end)
        it("should deinflect -tara: 食べたら → 食べる", function()
            assert.is_true(deinflectsTo("食べたら", "食べる"))
        end)
        it("should deinflect -tari: 食べたり → 食べる", function()
            assert.is_true(deinflectsTo("食べたり", "食べる"))
        end)
        it("should deinflect -zu: 食べず → 食べる", function()
            assert.is_true(deinflectsTo("食べず", "食べる"))
        end)
        it("should deinflect -nu: 食べぬ → 食べる", function()
            assert.is_true(deinflectsTo("食べぬ", "食べる"))
        end)
        it("should deinflect imperative negative: 食べるな → 食べる", function()
            assert.is_true(deinflectsTo("食べるな", "食べる"))
        end)
        it("should deinflect -chau: 食べちゃう → 食べる", function()
            assert.is_true(deinflectsTo("食べちゃう", "食べる"))
        end)
        it("should deinflect -chimau: 食べちまう → 食べる", function()
            assert.is_true(deinflectsTo("食べちまう", "食べる"))
        end)

        -- 見る (miru, see) — short ichidan stem
        it("should deinflect negative: 見ない → 見る", function()
            assert.is_true(deinflectsTo("見ない", "見る"))
        end)
        it("should deinflect te-form: 見て → 見る", function()
            assert.is_true(deinflectsTo("見て", "見る"))
        end)
        it("should deinflect past: 見た → 見る", function()
            assert.is_true(deinflectsTo("見た", "見る"))
        end)
    end)

    -- ================================================================
    -- Godan verbs (v5) — "u-verbs", all kana endings
    -- ================================================================
    describe("godan verbs", function()
        -- 書く (kaku, write) — ku ending
        describe("ku-ending: 書く", function()
            it("should deinflect negative: 書かない → 書く", function()
                assert.is_true(deinflectsTo("書かない", "書く"))
            end)
            it("should deinflect past: 書いた → 書く", function()
                assert.is_true(deinflectsTo("書いた", "書く"))
            end)
            it("should deinflect te-form: 書いて → 書く", function()
                assert.is_true(deinflectsTo("書いて", "書く"))
            end)
            it("should deinflect polite: 書きます → 書く", function()
                assert.is_true(deinflectsTo("書きます", "書く"))
            end)
            it("should deinflect conditional: 書けば → 書く", function()
                assert.is_true(deinflectsTo("書けば", "書く"))
            end)
            it("should deinflect volitional: 書こう → 書く", function()
                assert.is_true(deinflectsTo("書こう", "書く"))
            end)
            it("should deinflect imperative: 書け → 書く", function()
                assert.is_true(deinflectsTo("書け", "書く"))
            end)
            it("should deinflect potential: 書ける → 書く", function()
                assert.is_true(deinflectsTo("書ける", "書く"))
            end)
            it("should deinflect passive: 書かれる → 書く", function()
                assert.is_true(deinflectsTo("書かれる", "書く"))
            end)
            it("should deinflect causative: 書かせる → 書く", function()
                assert.is_true(deinflectsTo("書かせる", "書く"))
            end)
            it("should deinflect -tai: 書きたい → 書く", function()
                assert.is_true(deinflectsTo("書きたい", "書く"))
            end)
            it("should deinflect -zu: 書かず → 書く", function()
                assert.is_true(deinflectsTo("書かず", "書く"))
            end)
            it("should deinflect -tara: 書いたら → 書く", function()
                assert.is_true(deinflectsTo("書いたら", "書く"))
            end)
            it("should deinflect -tari: 書いたり → 書く", function()
                assert.is_true(deinflectsTo("書いたり", "書く"))
            end)
            it("should deinflect masu stem: 書き → 書く", function()
                assert.is_true(deinflectsTo("書き", "書く"))
            end)
        end)

        -- 泳ぐ (oyogu, swim) — gu ending
        describe("gu-ending: 泳ぐ", function()
            it("should deinflect negative: 泳がない → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳がない", "泳ぐ"))
            end)
            it("should deinflect past: 泳いだ → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳いだ", "泳ぐ"))
            end)
            it("should deinflect te-form: 泳いで → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳いで", "泳ぐ"))
            end)
            it("should deinflect polite: 泳ぎます → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳ぎます", "泳ぐ"))
            end)
            it("should deinflect conditional: 泳げば → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳げば", "泳ぐ"))
            end)
            it("should deinflect potential: 泳げる → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳げる", "泳ぐ"))
            end)
            it("should deinflect causative: 泳がせる → 泳ぐ", function()
                assert.is_true(deinflectsTo("泳がせる", "泳ぐ"))
            end)
        end)

        -- 話す (hanasu, speak) — su ending
        describe("su-ending: 話す", function()
            it("should deinflect negative: 話さない → 話す", function()
                assert.is_true(deinflectsTo("話さない", "話す"))
            end)
            it("should deinflect past: 話した → 話す", function()
                assert.is_true(deinflectsTo("話した", "話す"))
            end)
            it("should deinflect te-form: 話して → 話す", function()
                assert.is_true(deinflectsTo("話して", "話す"))
            end)
            it("should deinflect polite: 話します → 話す", function()
                assert.is_true(deinflectsTo("話します", "話す"))
            end)
            it("should deinflect conditional: 話せば → 話す", function()
                assert.is_true(deinflectsTo("話せば", "話す"))
            end)
            it("should deinflect potential: 話せる → 話す", function()
                assert.is_true(deinflectsTo("話せる", "話す"))
            end)
        end)

        -- 待つ (matsu, wait) — tsu ending
        describe("tsu-ending: 待つ", function()
            it("should deinflect negative: 待たない → 待つ", function()
                assert.is_true(deinflectsTo("待たない", "待つ"))
            end)
            it("should deinflect past: 待った → 待つ", function()
                assert.is_true(deinflectsTo("待った", "待つ"))
            end)
            it("should deinflect te-form: 待って → 待つ", function()
                assert.is_true(deinflectsTo("待って", "待つ"))
            end)
            it("should deinflect polite: 待ちます → 待つ", function()
                assert.is_true(deinflectsTo("待ちます", "待つ"))
            end)
            it("should deinflect conditional: 待てば → 待つ", function()
                assert.is_true(deinflectsTo("待てば", "待つ"))
            end)
        end)

        -- 死ぬ (shinu, die) — nu ending
        describe("nu-ending: 死ぬ", function()
            it("should deinflect negative: 死なない → 死ぬ", function()
                assert.is_true(deinflectsTo("死なない", "死ぬ"))
            end)
            it("should deinflect past: 死んだ → 死ぬ", function()
                assert.is_true(deinflectsTo("死んだ", "死ぬ"))
            end)
            it("should deinflect te-form: 死んで → 死ぬ", function()
                assert.is_true(deinflectsTo("死んで", "死ぬ"))
            end)
            it("should deinflect polite: 死にます → 死ぬ", function()
                assert.is_true(deinflectsTo("死にます", "死ぬ"))
            end)
            it("should deinflect conditional: 死ねば → 死ぬ", function()
                assert.is_true(deinflectsTo("死ねば", "死ぬ"))
            end)
        end)

        -- 遊ぶ (asobu, play) — bu ending
        describe("bu-ending: 遊ぶ", function()
            it("should deinflect negative: 遊ばない → 遊ぶ", function()
                assert.is_true(deinflectsTo("遊ばない", "遊ぶ"))
            end)
            it("should deinflect past: 遊んだ → 遊ぶ", function()
                assert.is_true(deinflectsTo("遊んだ", "遊ぶ"))
            end)
            it("should deinflect te-form: 遊んで → 遊ぶ", function()
                assert.is_true(deinflectsTo("遊んで", "遊ぶ"))
            end)
            it("should deinflect polite: 遊びます → 遊ぶ", function()
                assert.is_true(deinflectsTo("遊びます", "遊ぶ"))
            end)
            it("should deinflect conditional: 遊べば → 遊ぶ", function()
                assert.is_true(deinflectsTo("遊べば", "遊ぶ"))
            end)
        end)

        -- 読む (yomu, read) — mu ending
        describe("mu-ending: 読む", function()
            it("should deinflect negative: 読まない → 読む", function()
                assert.is_true(deinflectsTo("読まない", "読む"))
            end)
            it("should deinflect past: 読んだ → 読む", function()
                assert.is_true(deinflectsTo("読んだ", "読む"))
            end)
            it("should deinflect te-form: 読んで → 読む", function()
                assert.is_true(deinflectsTo("読んで", "読む"))
            end)
            it("should deinflect polite: 読みます → 読む", function()
                assert.is_true(deinflectsTo("読みます", "読む"))
            end)
            it("should deinflect conditional: 読めば → 読む", function()
                assert.is_true(deinflectsTo("読めば", "読む"))
            end)
        end)

        -- 取る (toru, take) — ru ending (godan, not ichidan)
        describe("ru-ending: 取る", function()
            it("should deinflect negative: 取らない → 取る", function()
                assert.is_true(deinflectsTo("取らない", "取る"))
            end)
            it("should deinflect past: 取った → 取る", function()
                assert.is_true(deinflectsTo("取った", "取る"))
            end)
            it("should deinflect te-form: 取って → 取る", function()
                assert.is_true(deinflectsTo("取って", "取る"))
            end)
            it("should deinflect polite: 取ります → 取る", function()
                assert.is_true(deinflectsTo("取ります", "取る"))
            end)
            it("should deinflect conditional: 取れば → 取る", function()
                assert.is_true(deinflectsTo("取れば", "取る"))
            end)
        end)

        -- 買う (kau, buy) — u ending
        describe("u-ending: 買う", function()
            it("should deinflect negative: 買わない → 買う", function()
                assert.is_true(deinflectsTo("買わない", "買う"))
            end)
            it("should deinflect past: 買った → 買う", function()
                assert.is_true(deinflectsTo("買った", "買う"))
            end)
            it("should deinflect te-form: 買って → 買う", function()
                assert.is_true(deinflectsTo("買って", "買う"))
            end)
            it("should deinflect polite: 買います → 買う", function()
                assert.is_true(deinflectsTo("買います", "買う"))
            end)
            it("should deinflect conditional: 買えば → 買う", function()
                assert.is_true(deinflectsTo("買えば", "買う"))
            end)
            it("should deinflect volitional: 買おう → 買う", function()
                assert.is_true(deinflectsTo("買おう", "買う"))
            end)
            it("should deinflect potential: 買える → 買う", function()
                assert.is_true(deinflectsTo("買える", "買う"))
            end)
        end)

        -- 行く (iku, go) — irregular te/past forms
        describe("irregular: 行く", function()
            it("should deinflect past: 行った → 行く", function()
                assert.is_true(deinflectsTo("行った", "行く"))
            end)
            it("should deinflect te-form: 行って → 行く", function()
                assert.is_true(deinflectsTo("行って", "行く"))
            end)
            it("should deinflect -tara: 行ったら → 行く", function()
                assert.is_true(deinflectsTo("行ったら", "行く"))
            end)
        end)
    end)

    -- ================================================================
    -- Suru verbs (vs)
    -- ================================================================
    describe("suru verbs", function()
        it("should deinflect negative: しない → する", function()
            assert.is_true(deinflectsTo("しない", "する"))
        end)
        it("should deinflect past: した → する", function()
            assert.is_true(deinflectsTo("した", "する"))
        end)
        it("should deinflect te-form: して → する", function()
            assert.is_true(deinflectsTo("して", "する"))
        end)
        it("should deinflect polite: します → する", function()
            assert.is_true(deinflectsTo("します", "する"))
        end)
        it("should deinflect polite negative: しません → する", function()
            assert.is_true(deinflectsTo("しません", "する"))
        end)
        it("should deinflect polite past: しました → する", function()
            assert.is_true(deinflectsTo("しました", "する"))
        end)
        it("should deinflect polite past negative: しませんでした → する", function()
            assert.is_true(deinflectsTo("しませんでした", "する"))
        end)
        it("should deinflect polite volitional: しましょう → する", function()
            assert.is_true(deinflectsTo("しましょう", "する"))
        end)
        it("should deinflect conditional: すれば → する", function()
            assert.is_true(deinflectsTo("すれば", "する"))
        end)
        it("should deinflect volitional: しよう → する", function()
            assert.is_true(deinflectsTo("しよう", "する"))
        end)
        it("should deinflect imperative: しろ → する", function()
            assert.is_true(deinflectsTo("しろ", "する"))
        end)
        it("should deinflect imperative (seyo): せよ → する", function()
            assert.is_true(deinflectsTo("せよ", "する"))
        end)
        it("should deinflect causative: させる → する", function()
            assert.is_true(deinflectsTo("させる", "する"))
        end)
        it("should deinflect passive: される → する", function()
            assert.is_true(deinflectsTo("される", "する"))
        end)
        it("should deinflect -tai: したい → する", function()
            assert.is_true(deinflectsTo("したい", "する"))
        end)
        it("should deinflect -nasai: しなさい → する", function()
            assert.is_true(deinflectsTo("しなさい", "する"))
        end)
        it("should deinflect -sou: しそう → する", function()
            assert.is_true(deinflectsTo("しそう", "する"))
        end)
        it("should deinflect -sugiru: しすぎる → する", function()
            assert.is_true(deinflectsTo("しすぎる", "する"))
        end)
        it("should deinflect -zu: せず → する", function()
            assert.is_true(deinflectsTo("せず", "する"))
        end)
        it("should deinflect -nu: せぬ → する", function()
            assert.is_true(deinflectsTo("せぬ", "する"))
        end)
        it("should deinflect -toku: しとく → する", function()
            assert.is_true(deinflectsTo("しとく", "する"))
        end)
        it("should deinflect -chau: しちゃう → する", function()
            assert.is_true(deinflectsTo("しちゃう", "する"))
        end)

        -- 為る kanji variant
        it("should deinflect imperative (kanji): 為ろ → 為る", function()
            assert.is_true(deinflectsTo("為ろ", "為る"))
        end)
    end)

    -- ================================================================
    -- Kuru verbs (vk)
    -- ================================================================
    describe("kuru verbs", function()
        -- くる (hiragana)
        it("should deinflect negative: こない → くる", function()
            assert.is_true(deinflectsTo("こない", "くる"))
        end)
        it("should deinflect past: きた → くる", function()
            assert.is_true(deinflectsTo("きた", "くる"))
        end)
        it("should deinflect te-form: きて → くる", function()
            assert.is_true(deinflectsTo("きて", "くる"))
        end)
        it("should deinflect polite: きます → くる", function()
            assert.is_true(deinflectsTo("きます", "くる"))
        end)
        it("should deinflect polite negative: きません → くる", function()
            assert.is_true(deinflectsTo("きません", "くる"))
        end)
        it("should deinflect polite past: きました → くる", function()
            assert.is_true(deinflectsTo("きました", "くる"))
        end)
        it("should deinflect conditional: くれば → くる", function()
            assert.is_true(deinflectsTo("くれば", "くる"))
        end)
        it("should deinflect volitional: こよう → くる", function()
            assert.is_true(deinflectsTo("こよう", "くる"))
        end)
        it("should deinflect imperative: こい → くる", function()
            assert.is_true(deinflectsTo("こい", "くる"))
        end)
        it("should deinflect causative: こさせる → くる", function()
            assert.is_true(deinflectsTo("こさせる", "くる"))
        end)
        it("should deinflect passive: こられる → くる", function()
            assert.is_true(deinflectsTo("こられる", "くる"))
        end)
        it("should deinflect potential: これる → くる", function()
            assert.is_true(deinflectsTo("これる", "くる"))
        end)
        it("should deinflect -zu: こず → くる", function()
            assert.is_true(deinflectsTo("こず", "くる"))
        end)
        it("should deinflect -toku: きとく → くる", function()
            assert.is_true(deinflectsTo("きとく", "くる"))
        end)
        it("should deinflect masu stem: き → くる", function()
            assert.is_true(deinflectsTo("き", "くる"))
        end)

        -- 来る (kanji)
        it("should deinflect past (kanji): 来た → 来る", function()
            assert.is_true(deinflectsTo("来た", "来る"))
        end)
        it("should deinflect te-form (kanji): 来て → 来る", function()
            assert.is_true(deinflectsTo("来て", "来る"))
        end)
        it("should deinflect negative (kanji): 来ない → 来る", function()
            assert.is_true(deinflectsTo("来ない", "来る"))
        end)
        it("should deinflect polite (kanji): 来ます → 来る", function()
            assert.is_true(deinflectsTo("来ます", "来る"))
        end)
        it("should deinflect imperative (kanji): 来い → 来る", function()
            assert.is_true(deinflectsTo("来い", "来る"))
        end)
    end)

    -- ================================================================
    -- Zuru verbs (vz)
    -- ================================================================
    describe("zuru verbs", function()
        -- 感ずる (kanzuru, to feel)
        it("should deinflect negative: 感じない → 感ずる", function()
            assert.is_true(deinflectsTo("感じない", "感ずる"))
        end)
        it("should deinflect past: 感じた → 感ずる", function()
            assert.is_true(deinflectsTo("感じた", "感ずる"))
        end)
        it("should deinflect te-form: 感じて → 感ずる", function()
            assert.is_true(deinflectsTo("感じて", "感ずる"))
        end)
        it("should deinflect polite: 感じます → 感ずる", function()
            assert.is_true(deinflectsTo("感じます", "感ずる"))
        end)
        it("should deinflect polite negative: 感じません → 感ずる", function()
            assert.is_true(deinflectsTo("感じません", "感ずる"))
        end)
        it("should deinflect polite past: 感じました → 感ずる", function()
            assert.is_true(deinflectsTo("感じました", "感ずる"))
        end)
        it("should deinflect polite past negative: 感じませんでした → 感ずる", function()
            assert.is_true(deinflectsTo("感じませんでした", "感ずる"))
        end)
        it("should deinflect polite volitional: 感じましょう → 感ずる", function()
            assert.is_true(deinflectsTo("感じましょう", "感ずる"))
        end)
        it("should deinflect conditional: 感ずれば → 感ずる", function()
            assert.is_true(deinflectsTo("感ずれば", "感ずる"))
        end)
        it("should deinflect volitional: 感じよう → 感ずる", function()
            assert.is_true(deinflectsTo("感じよう", "感ずる"))
        end)
        it("should deinflect imperative: 感じろ → 感ずる", function()
            assert.is_true(deinflectsTo("感じろ", "感ずる"))
        end)
        it("should deinflect imperative (zeyo): 感ぜよ → 感ずる", function()
            assert.is_true(deinflectsTo("感ぜよ", "感ずる"))
        end)
        it("should deinflect causative: 感じさせる → 感ずる", function()
            assert.is_true(deinflectsTo("感じさせる", "感ずる"))
        end)
        it("should deinflect causative (ze-): 感ぜさせる → 感ずる", function()
            assert.is_true(deinflectsTo("感ぜさせる", "感ずる"))
        end)
        it("should deinflect passive: 感じされる → 感ずる", function()
            assert.is_true(deinflectsTo("感じされる", "感ずる"))
        end)
        it("should deinflect potential/passive: 感ざれる → 感ずる", function()
            assert.is_true(deinflectsTo("感ざれる", "感ずる"))
        end)
        it("should deinflect potential/passive (ze-): 感ぜられる → 感ずる", function()
            assert.is_true(deinflectsTo("感ぜられる", "感ずる"))
        end)
        it("should deinflect -tai: 感じたい → 感ずる", function()
            assert.is_true(deinflectsTo("感じたい", "感ずる"))
        end)
        it("should deinflect -nasai: 感じなさい → 感ずる", function()
            assert.is_true(deinflectsTo("感じなさい", "感ずる"))
        end)
        it("should deinflect -sou: 感じそう → 感ずる", function()
            assert.is_true(deinflectsTo("感じそう", "感ずる"))
        end)
        it("should deinflect -sugiru: 感じすぎる → 感ずる", function()
            assert.is_true(deinflectsTo("感じすぎる", "感ずる"))
        end)
        it("should deinflect -tara: 感じたら → 感ずる", function()
            assert.is_true(deinflectsTo("感じたら", "感ずる"))
        end)
        it("should deinflect -tari: 感じたり → 感ずる", function()
            assert.is_true(deinflectsTo("感じたり", "感ずる"))
        end)
        it("should deinflect -zu: 感ぜず → 感ずる", function()
            assert.is_true(deinflectsTo("感ぜず", "感ずる"))
        end)
        it("should deinflect -nu: 感ぜぬ → 感ずる", function()
            assert.is_true(deinflectsTo("感ぜぬ", "感ずる"))
        end)
        it("should deinflect -toku: 感じとく → 感ずる", function()
            assert.is_true(deinflectsTo("感じとく", "感ずる"))
        end)
        it("should deinflect -chau: 感じちゃう → 感ずる", function()
            assert.is_true(deinflectsTo("感じちゃう", "感ずる"))
        end)
        it("should deinflect -chimau: 感じちまう → 感ずる", function()
            assert.is_true(deinflectsTo("感じちまう", "感ずる"))
        end)
    end)

    -- ================================================================
    -- Multi-step deinflection chains
    -- ================================================================
    describe("multi-step chains", function()
        -- te-form + progressive: 食べている → 食べる
        it("should deinflect progressive: 食べている → 食べる", function()
            assert.is_true(deinflectsTo("食べている", "食べる"))
        end)
        it("should deinflect progressive (contracted): 食べてる → 食べる", function()
            assert.is_true(deinflectsTo("食べてる", "食べる"))
        end)
        it("should deinflect progressive (おる): 食べておる → 食べる", function()
            assert.is_true(deinflectsTo("食べておる", "食べる"))
        end)
        it("should deinflect progressive (contracted おる): 食べとる → 食べる", function()
            assert.is_true(deinflectsTo("食べとる", "食べる"))
        end)
        -- te-form + shimau
        it("should deinflect -te + shimau: 食べてしまう → 食べる", function()
            assert.is_true(deinflectsTo("食べてしまう", "食べる"))
        end)
        -- negative + past (already single-step, but verifies chaining)
        it("should deinflect negative past: 食べなかった → 食べる", function()
            assert.is_true(deinflectsTo("食べなかった", "食べる"))
        end)
        -- polite negative past
        it("should deinflect polite negative past: 食べませんでした → 食べる", function()
            assert.is_true(deinflectsTo("食べませんでした", "食べる"))
        end)
        -- causative + passive
        it("should deinflect causative passive: 書かされる → 書く", function()
            assert.is_true(deinflectsTo("書かされる", "書く"))
        end)
        -- -chau + past (colloquial past completion)
        it("should deinflect -chau + past: 食べちゃった → 食べる", function()
            assert.is_true(deinflectsTo("食べちゃった", "食べる"))
        end)

        -- godan te-form + progressive
        it("should deinflect godan progressive: 書いている → 書く", function()
            assert.is_true(deinflectsTo("書いている", "書く"))
        end)
        it("should deinflect godan progressive (contracted): 書いてる → 書く", function()
            assert.is_true(deinflectsTo("書いてる", "書く"))
        end)

        -- zuru progressive
        it("should deinflect zuru progressive: 感じている → 感ずる", function()
            assert.is_true(deinflectsTo("感じている", "感ずる"))
        end)
        it("should deinflect zuru progressive (contracted): 感じてる → 感ずる", function()
            assert.is_true(deinflectsTo("感じてる", "感ずる"))
        end)
    end)

    -- ================================================================
    -- Text conversions (katakana, halfwidth, etc.)
    -- ================================================================
    describe("text conversions", function()
        -- Katakana to hiragana conversion (enabled by default)
        it("should deinflect katakana input: タベル → 食べる candidate via たべる", function()
            assert.is_true(deinflectsFull("タベナイ", "たべない"))
        end)
        it("should deinflect katakana negative: タベナイ deinflects to たべる", function()
            assert.is_true(deinflectsFull("タベナイ", "たべる"))
        end)

        -- Halfwidth katakana (enabled by default)
        it("should deinflect halfwidth katakana: ﾀﾍﾞﾙ converts to fullwidth", function()
            assert.is_true(deinflectsFull("ﾀﾍﾞﾙ", "タベル"))
        end)
    end)
end)
