describe("QuickStart module", function()
    setup(function()
        require("commonrequire")  
    end)
    it("should return false shown_version lower than force_show_version", function()
        G_reader_settings:saveSetting("quickstart_shown_version", 1)
        G_reader_settings:flush()
        local QuickStart = require("ui/quickstart")
        QuickStart.quickstart_force_show_version = 2
        assert.is_false(QuickStart:isShown())
    end)
    it("should return true when shown_version equal to force_show_version", function()
        G_reader_settings:saveSetting("quickstart_shown_version", 1)
        G_reader_settings:flush()
        local QuickStart = require("ui/quickstart")
        QuickStart.quickstart_force_show_version = 1
        assert.is_true(QuickStart:isShown())
    end)
    it("should return true when shown_version higher than force_show_version", function()
        G_reader_settings:saveSetting("quickstart_shown_version", 2)
        G_reader_settings:flush()
        local QuickStart = require("ui/quickstart")
        QuickStart.quickstart_force_show_version = 1
        assert.is_true(QuickStart:isShown())
    end)
end)
