#!/bin/sh
export LC_ALL="en_US.UTF-8"

# working directory of koreader
KOREADER_DIR="${0%/*}"

# we're always starting from our working directory
cd "${KOREADER_DIR}" || exit

RETURN_VALUE=85

while [ ${RETURN_VALUE} -eq 85 ]; do
    ./reader.lua "$@"
    RETURN_VALUE=$?
done

exit ${RETURN_VALUE}
