#!/bin/sh

# working directory of koreader
KOREADER_DIR="${0%/*}"

# we're always starting from our working directory
cd "${KOREADER_DIR}" || exit

RETURN_VALUE=85

while [ ${RETURN_VALUE} -eq 85 ]; do
    ./koreader "${*}
    RETURN_VALUE=$?
done

exit ${RETURN_VALUE}
