-- tell calibre which extensions are supported by the client
local user_path = require("datastorage"):getDataDir() .. "/calibre-extensions.lua"
local ok, extensions = pcall(dofile, user_path)

if ok then
    return extensions
else
    return {
        "azw",
        "cbz",
        "chm",
        "djv",
        "djvu",
        "doc",
        "docx",
        "epub",
        "fb2",
        "htm",
        "html",
        "md",
        "mobi",
        "pdb",
        "pdf",
        "prc",
        "rtf",
        "txt",
        "xhtml",
        "xps",
        "zip",
    }
end

--[[ calibre valid extensions
{
    [1] = "lrf",
    [2] = "rar",
    [3] = "zip",
    [4] = "rtf",
    [5] = "lit",
    [6] = "txt",
    [7] = "txtz",
    [8] = "text",
    [9] = "htm",
    [10] = "xhtm",
    [11] = "html",
    [12] = "htmlz",
    [13] = "xhtml",
    [14] = "pdf",
    [15] = "pdb",
    [16] = "updb",
    [17] = "pdr",
    [18] = "prc",
    [19] = "mobi",
    [20] = "azw",
    [21] = "doc",
    [22] = "epub",
    [23] = "fb2",
    [24] = "fbz",
    [25] = "djv",
    [26] = "djvu",
    [27] = "lrx",
    [28] = "cbr",
    [29] = "cbz",
    [30] = "cbc",
    [31] = "oebzip",
    [32] = "rb",
    [33] = "imp",
    [34] = "odt",
    [35] = "chm",
    [36] = "tpz",
    [37] = "azw1",
    [38] = "pml",
    [39] = "pmlz",
    [40] = "mbp",
    [41] = "tan",
    [42] = "snb",
    [43] = "xps",
    [44] = "oxps",
    [45] = "azw4",
    [46] = "book",
    [47] = "zbf",
    [48] = "pobi",
    [49] = "docx",
    [50] = "docm",
    [51] = "md",
    [52] = "textile",
    [53] = "markdown",
    [54] = "ibook",
    [55] = "ibooks",
    [56] = "iba",
    [57] = "azw3",
    [58] = "ps",
    [59] = "kepub",
    [60] = "kfx",
    [61] = "kpf"
}
]]--

