--[[--This module is responsible for generating the quickstart guide.
]]
local DataStorage = require("datastorage")
local FileConverter = require("apps/filemanager/filemanagerconverter")
local gettext = require("gettext")
local lfs = require("libs/libkoreader-lfs")
local T = require("ffi/util").template

local quickstart_shown = G_reader_settings:readSetting("quickstart_shown") or nil
local quickstart_shown_version = G_reader_settings:readSetting("quickstart_shown_version") or nil
local quickstart_force_show_version = 201511982
local language = G_reader_settings:readSetting("language") or "en"
local version, _, rev = G_reader_settings:current_version()

local quickstart_guide = T(gettext([[
# KOReader Quickstart Guide

Welcome to KOreader. You can activate the menu by swiping down from the top of the screen. Clicking outside the menu or swiping up on the menu will discard it. Turning pages can be done either by swiping left and right or by single taps on the left or right side of the screen.

**Main menu**

![Menu](../resources/icons/menu-icon.png) You can always view this quickstart guide again through *Help* → *Quickstart guide* in the top right menu.

**Settings**

![Settings](../resources/icons/appbar.settings.png) You can change the language and other settings through the gear icon.

------------

Generated by KOReader %1.
]]),
    rev)

local QuickStart = {}

--[[-- Returns `true` if shown, `false` if the quickstart guide hasn't been
shown yet or if display is forced through a higher version number than when
it was first shown.
]]
function QuickStart:isShown()
    if quickstart_shown and not (quickstart_shown_version < quickstart_force_show_version) then return true end
    return false
end

--[[--Generates the quickstart guide in the user's language and returns its location.

The fileformat is `quickstart-en-v2015.11-985-g88308992.html`, `en` being the
language of the generated file and `v2015.11-985-g88308992` the KOReader version
used to generate the file.

@treturn string path to generated HTML quickstart guide
]]
function QuickStart:getQuickStart()
    local quickstart_dir = string.format("%s%s", DataStorage:getDataDir(), "/help")
    local quickstart_filename = string.format("%s%s%s%s%s%s", quickstart_dir, "/quickstart-", language, "-", rev, ".html")
    if lfs.attributes(quickstart_dir, "mode") ~= "dir" then
        lfs.mkdir(quickstart_dir)
    end
    if lfs.attributes(quickstart_filename, "mode") ~= "file" then
        local quickstart_html = FileConverter:mdToHtml(quickstart_guide, T(gettext("KOReader Quickstart Guide")))
        if quickstart_html then
            FileConverter:writeStringToFile(quickstart_html, quickstart_filename)
        end
    end
    G_reader_settings:saveSetting("quickstart_shown_version", version)
    G_reader_settings:flipTrue("quickstart_shown")
    return quickstart_filename
end

return QuickStart
