#!/usr/bin/env python3

# Copyright (c) 2021 Aleksa Sarai <cyphar@cyphar.com>
# Licensed under the GPLv3-or-later.
#
# usage: ./tools/ja_keyboard_generate_modifiers.py > frontend/ui/data/keyboardlayouts/ja_keyboard_modifiers.lua
#
# Generates the modifier cycle table for the Japanese 12-key flick keyboard,
# the goal being to create an efficient mapping for each kana so that when a
# given modifier is pressed we can easily switch to the next key. Each kana is
# part of a cycle so pressing the modifier key multiple times will loop through
# the options.

import os
import unicodedata

def NFC(s): return unicodedata.normalize("NFC", s)
def NFD(s): return unicodedata.normalize("NFD", s)

RAW_DAKUTEN = "\u3099"
RAW_HANDAKUTEN = "\u309A"

def modified_kana(kana):
	# Try to produce versions of the kana which are combined with dakuten or
	# handakuten. We only care about combined versions of the character if the
	# combined version is a single codepoint (which means it's a "standard"
	# combination and is thus a valid modified version of the given kana).
	#
	# Python3's len() counts the number of codepoints, which is what we want.
	return [ NFC(kana+modifier)
			 for modifier in [RAW_DAKUTEN, RAW_HANDAKUTEN]
				 if len(NFC(kana+modifier)) == 1 ]

# Hiragana and katakana without any dakuten.
BASE_KANA = "あいえうおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわを" + \
			"アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲ"

MODIFIED_KANA = "".join("".join(modified_kana(kana)) for kana in BASE_KANA)

# The set of small kana (from their big kana equivalent).
SMALL_KANA = {
	# Hiragana
	"あ": "ぁ", "い": "ぃ", "う": "ぅ", "え": "ぇ", "お": "ぉ",
	"や": "ゃ",             "ゆ": "ゅ",             "よ": "ょ",
	"わ": "ゎ",             "つ": "っ",

	# Katakana
	"ア": "ァ", "イ": "ィ", "ウ": "ゥ", "エ": "ェ", "オ": "ォ",
	"ヤ": "ャ",             "ユ": "ュ",             "ヨ": "ョ",
	"ワ": "ヮ",             "ツ": "ッ",
}

EN_ALPHABET = "abcdefghijklmnopqrstuvwxyz"

def generate_cycle(kana):
	"Generate an array describing the modifier cycle for a given kana."

	# The cycle starts with the provided kana.
	cycle = [kana]
	# If there are any small kana, add them to the cycle.
	if kana in SMALL_KANA:
		cycle.append(SMALL_KANA[kana])
	# If there are any valid modifications of this kana, add them to the cycle.
	cycle.extend(modified_kana(kana))
	return cycle

def generate_basic_cycle(kana, modifier):
	"""
	Generate an array describing a basic cycle using just the given combining
	mark.
	"""
	cycle = [NFC(kana)]
	base_kana, *_ = NFD(kana) # Remove any combining marks.
	new_kana = NFC(base_kana + modifier)
	if new_kana != kana and len(new_kana) == 1:
		cycle.append(new_kana)
	return cycle

def generate_alphabet_shift_cycle(letter):
	return [letter, letter.upper()]

def output_cycle(cycle, loop=True):
	"Return a snippet of a Lua table describing the cycle passed."
	cycle = list(cycle)
	if len(cycle) == 1:
		return "" # Don't do anything for noop one-kana cycles.
	if loop:
		# Map the last kana back to the start.
		mapping = zip(cycle, cycle[1:] + [cycle[0]])
	else:
		# The last kana doesn't get any mapping.
		mapping = zip(cycle, cycle[1:])
	lua_snippet = []
	for kana_src, kana_dst in mapping:
		lua_snippet.append('[ "%s" ] = "%s",' % (kana_src, kana_dst))
	return " ".join(lua_snippet)

def indent(table, level):
	return "\n".join(" "*level+line for line in table if line != "")

# Straight-forward cycle over all options.
cyclic_table = [ output_cycle(generate_cycle(kana)) for kana in BASE_KANA ]

# For the dakuten table we want to include handakuten -> dakuten conversions so use MODIFIED_KANA but with looping disabled.
dakuten_table = \
	[ output_cycle(generate_basic_cycle(kana, RAW_DAKUTEN)) for kana in BASE_KANA ] + \
	[ output_cycle(generate_basic_cycle(kana, RAW_DAKUTEN), loop=False) for kana in MODIFIED_KANA ]

# Ditto for handakuten.
handakuten_table = \
	[ output_cycle(generate_basic_cycle(kana, RAW_HANDAKUTEN)) for kana in BASE_KANA ] + \
	[ output_cycle(generate_basic_cycle(kana, RAW_HANDAKUTEN), loop=False) for kana in MODIFIED_KANA ]

# For the shift table.
shift_table = [ output_cycle(generate_alphabet_shift_cycle(letter)) for letter in EN_ALPHABET ]

print(f"""
--- @note This was generated with tools/ja_keyboard_generate_modifiers.py.
-- DO NOT EDIT THIS FILE MANUALLY. Instead, edit and re-run the script.

local MODIFIER_CYCLIC = "変換"
local MODIFIER_DAKUTEN = "◌゙"
local MODIFIER_HANDAKUTEN = "◌゚"
local MODIFIER_SHIFT = "\uED35"

return {{
    MODIFIER_CYCLIC = MODIFIER_CYCLIC,
    MODIFIER_DAKUTEN = MODIFIER_DAKUTEN,
    MODIFIER_HANDAKUTEN = MODIFIER_HANDAKUTEN,
    MODIFIER_SHIFT = MODIFIER_SHIFT,
    MODIFIER_TABLE = {{
        [MODIFIER_DAKUTEN] = {{
{indent(dakuten_table, 3*4)}
        }},
        [MODIFIER_HANDAKUTEN] = {{
{indent(handakuten_table, 3*4)}
        }},
        [MODIFIER_SHIFT] = {{
{indent(shift_table, 3*4)}
        }},
        [MODIFIER_CYCLIC] = {{
{indent(cyclic_table, 3*4)}
        }},
    }},
}}
""")
