#!/bin/sh

## First arg is the checkpoint counter, and we get one every 200 blocks (tar's default blocksize is 20 * 512).
## While we can compute an accurate total number of blocks when unpacking a tarball,
## it appears to be much harder to do it right when *creating* a tarball...
## (especially in our case, because we're creating one from a list of files, not a single file/direcotry).
CHECKPOINT_NUM="${1}"
CHECKPOINT_GRANULARITY="200"
# This usually amounts to around ~32 checkpoints in our case, which is probably why I initially settled on this value,
# because that's close to the amount of columns in a single line in most of our target devices.
# In short, yes, lucky magic number :D.

# Use that to build a progress bar
PROGRESS_AMOUNT="$((CHECKPOINT_NUM / CHECKPOINT_GRANULARITY))"

# And start drawing the progress bar...
PROGRESS_STRING=""
for _ in $(seq 1 ${PROGRESS_AMOUNT}); do
    # Fill the progress bar...
    PROGRESS_STRING="${PROGRESS_STRING}."
done

# Print our progress :)
./fbink -q -y -6 -pmh "${PROGRESS_STRING}"
