#!/bin/sh

# We're going to need to remember failures from the *left* side of a pipeline...
set -o pipefail

# Figure out whether that's a delta or a full download given the number of arguments passed...
if [ $# -lt 7 ]; then
    ZSYNC_MESSAGE="Downloading update data"
else
    ZSYNC_MESSAGE="Computing zsync delta"
fi

# Small zsync wrapper so we can print its output while it works...
./fbink -q -y -7 -pmh "${ZSYNC_MESSAGE} . . ."
# Clear any potential leftover from the local OTA tarball creation.
./fbink -q -y -6 -pm ' '

# Launch zsync2, and remember its exit code...
# We'll be piping its output to FBInk in order to print it live, in a smaller font than usual...
# NOTE: This depends on an undocumented FBInk hack (-z) in order to deal with the progress bars (and their CR) sanely.
# NOTE: As usual, redirect FBInk's stderr to /dev/null because of the "missing codepoint" warnings ;).
./zsync2 "$@" 2>&1 | ./fbink -q -z -pm -F scientifica 2>/dev/null
rc=$?

# And return with zsync's exit code, not kill's ;).
exit ${rc}
