# This workflow is managed by gh actions-lock.

name: Cache cleanup

permissions:
  actions: write

on:
  pull_request:
    types:
      - closed

jobs:

  cleanup:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
          sparse-checkout: .ci
      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.ci/cache_cleanup.sh refs/pull/${{ github.event.pull_request.number }}/merge
