name: CI tests

defaults:
  run:
    shell: bash

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Path: ~/local/bin"
        run: echo ~/local/bin >> $GITHUB_PATH

      - name: Install luarocks
        run:  curl -sSL "https://raw.githubusercontent.com/koreader/virdevenv/master/docker/ubuntu/baseimage/install_luarocks.sh" | sudo bash

      - name: Install Lint
        run:  curl -sSL "https://raw.githubusercontent.com/koreader/virdevenv/master/docker/ubuntu/baseimage/install_lint.sh" | bash -s ~

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check
        run: ./kodev check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
        EMULATE_READER: 1
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - name: Install
        run: sudo apt-get install -y gettext ccache ninja-build libtool-bin libsdl2-2.0-0

      - name: Install luarocks
        run:  curl -sSL "https://raw.githubusercontent.com/koreader/virdevenv/master/docker/ubuntu/baseimage/install_luarocks.sh" | sudo bash

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # need to init some stuff first or git will complain when sticking in base cache
      - name: Init base submodule
        run: git submodule init base && git submodule update base && pushd base && git submodule init && git submodule update && popd

      - name: base cache check
        run: pushd base && git_rev_base=$(git describe HEAD) && popd && echo $git_rev_base && echo $git_rev_base >git-rev-base

      - name: Cache base
        uses: actions/cache@v2
        with:
            path: |
                ~/.ccache
                base
            key: ${{ matrix.os }}-build-${{ hashFiles('git-rev-base') }}

      - name: Build
        run: ./kodev build

      - name: Test
        run: ./kodev test front
