name: CI tests

defaults:
  run:
    shell: bash

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        EMULATE_READER: 1
        # pretend to be cirleci so the scripts dont have to change
        CIRCLE_WORKING_DIRECTORY: ${{ github.workspace }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y luarocks gettext ccache

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # need to init some stuff first or git will complain when sticking in base cache
      - name: Init base submodule
        run: git submodule init base && git submodule update base && pushd base && git submodule init && git submodule update && popd

      - name: base cache check
        run: pushd base && git_rev_base=$(git describe HEAD) && popd && echo $git_rev_base && echo $git_rev_base >git-rev-base

      - name: Cache base
        uses: actions/cache@v2
        with:
            path: |
                .ccache
                base
            key: build-${{ hashFiles('git-rev-base') }}

      - name: Build
        run: ./kodev build

#      - name: install
#        run: .ci/install.sh
#
#      - name: fetch
#        run: .ci/fetch.sh
#
#      - name: check
#        run: .ci/check.sh
#
#      - name:  build
#        run: .ci/build.sh
#
#      - name:  test
#        run: .ci/test.sh
#
#      - name:  docs-and-coverage
#        # only run when the event is a push on the master branch
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#        run: .ci/github_after_success.sh
#
